### ISSUE TITLE
Can not compile  pg_pathman-1.4.11 with PostgreSQL 10.4 

### ISSUE THREAD

**Issue by myaniu** [postgrespro/pg_pathman#156]
Problem description
Can not compile  pg_pathman-1.4.11 with PostgreSQL 10.4

error message:

gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -g -O2 -DMAP_HUGETLB=0x40000 -fPIC -I/root/pg_pathman-1.4.11/src/include -I. -I./ -I/server/PostgreSQL/10/include/postgresql/server -I/server/PostgreSQL/10/include/postgresql/internal -I/opt/local/Current/include -D_GNU_SOURCE  -I/opt/local/Current/include/libxml2 -I/opt/local/Current/include  -c -o src/hooks.o src/hooks.c
src/hooks.c: In function ‘pathman_join_pathlist_hook’:
src/hooks.c:169: warning: passing argument 2 of ‘extract_actual_join_clauses’ from incompatible pointer type
/server/PostgreSQL/10/include/postgresql/server/optimizer/restrictinfo.h:38: note: expected ‘Relids’ but argument is of type ‘struct List **’
src/hooks.c:169: error: too few arguments to function ‘extract_actual_join_clauses’
make: *** [src/hooks.o] Error 1

### Environment

extname  | extowner | extnamespace | extrelocatable | extversion | extconfig | extcondition
-----------+----------+--------------+----------------+------------+-----------+--------------
 plpgsql   |       10 |           11 | f              | 1.0        |           |
 adminpack |       10 |           11 | f              | 1.1        |           |
(2 rows)

 PostgreSQL 10.4 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18), 64-bit
(1 row)

I compared the source  of PostgreSQL 10.s and PostgreSQL 10.4 .
PostgreSQL 10.4  add parameter "Relids joinrelids" to  function "extract_actual_join_clauses"
that is declared in file: src/include/optimizer/restrictinfo.h

**Comment by funbringer** [comment]
Hi @myaniu,

Please try building `master` branch. Does it work for you? If so, we'll publish a new minor release.

**Comment by funbringer** [comment]
We've released [1.4.12](https://github.com/postgrespro/pg_pathman/releases/tag/1.4.12) that should compile with 10.4.

**Comment by myaniu** [comment]
It works, thanks.
